const statusOptions = [
  { value: 'pending', label: 'Pending', icon: '○' },
  { value: 'completed', label: 'Completed', icon: '✓' },
  { value: 'overdue', label: 'Overdue', icon: '⚠' },
];

const priorityOptions = [
  {
    value: 'high',
    label: 'High Priority',
    description: 'Urgent tasks that need immediate attention',
  },
  {
    value: 'medium',
    label: 'Medium Priority',
    description: 'Important tasks with moderate timeline',
  },
  {
    value: 'low',
    label: 'Low Priority',
    description: 'Tasks that can be completed when time allows',
  },
];
const sampleTasks = [
  {
    id: 1,
    title: 'Complete project documentation',
    description: 'Write comprehensive docs for the new feature',
    updatedAt: '2024-09-26 10:30 AM',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-09-27',
  },
  {
    id: 2,
    title: 'Review code changes',
    description: 'Review pull requests from team members',
    updatedAt: '2024-09-26 09:15 AM',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-09-26',
  },
  {
    id: 3,
    title: 'Update mobile app',
    description: '',
    updatedAt: '2024-09-25 04:20 PM',
    status: 'pending',
    priority: 'low',
    dueDate: '2024-09-28',
  },
  {
    id: 4,
    title: 'Prepare presentation slides',
    description: 'Create slides for quarterly review meeting',
    updatedAt: '2024-09-25 02:45 PM',
    status: 'overdue',
    priority: 'high',
    dueDate: '2024-09-24',
  },
  {
    id: 5,
    title: 'Database backup',
    description: 'Perform weekly database backup and verification',
    updatedAt: '2024-09-24 11:00 AM',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-09-24',
  },
  {
    id: 6,
    title: 'Design new logo',
    description: 'Create a fresh logo concept for marketing',
    updatedAt: '2024-09-26 01:10 PM',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-09-30',
  },
  {
    id: 7,
    title: 'Fix login bug',
    description: 'Resolve authentication error in mobile app',
    updatedAt: '2024-09-26 08:45 AM',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-09-27',
  },
  {
    id: 8,
    title: 'Prepare budget report',
    description: 'Analyze last month’s expenses and prepare report',
    updatedAt: '2024-09-25 03:00 PM',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-09-25',
  },
  {
    id: 9,
    title: 'Update website homepage',
    description: 'Refresh homepage banner and call-to-action',
    updatedAt: '2024-09-24 12:15 PM',
    status: 'pending',
    priority: 'low',
    dueDate: '2024-09-29',
  },
  {
    id: 10,
    title: 'Team feedback meeting',
    description: 'Gather feedback from team on recent changes',
    updatedAt: '2024-09-23 10:00 AM',
    status: 'completed',
    priority: 'low',
    dueDate: '2024-09-23',
  },
  {
    id: 11,
    title: 'Integrate payment gateway',
    description: 'Implement Stripe for subscription payments',
    updatedAt: '2024-09-26 11:45 AM',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-09-30',
  },
  {
    id: 12,
    title: 'Clean up database',
    description: 'Remove unused records and optimize queries',
    updatedAt: '2024-09-25 09:30 AM',
    status: 'overdue',
    priority: 'medium',
    dueDate: '2024-09-24',
  },
  {
    id: 13,
    title: 'Plan team outing',
    description: 'Decide location and activities for team outing',
    updatedAt: '2024-09-24 04:00 PM',
    status: 'pending',
    priority: 'low',
    dueDate: '2024-10-05',
  },
  {
    id: 14,
    title: 'Update privacy policy',
    description: 'Ensure compliance with new regulations',
    updatedAt: '2024-09-26 02:30 PM',
    status: 'pending',
    priority: 'medium',
    dueDate: '2024-10-01',
  },
  {
    id: 15,
    title: 'Conduct user interviews',
    description: 'Gather feedback on new UI changes',
    updatedAt: '2024-09-25 05:00 PM',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-09-25',
  },
  {
    id: 16,
    title: 'Optimize app performance',
    description: 'Reduce load time and memory usage',
    updatedAt: '2024-09-26 03:20 PM',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-10-02',
  },
  {
    id: 17,
    title: 'Test new features',
    description: 'Run QA on upcoming release',
    updatedAt: '2024-09-25 08:10 AM',
    status: 'overdue',
    priority: 'high',
    dueDate: '2024-09-24',
  },
  {
    id: 18,
    title: 'Create onboarding tutorial',
    description: 'Develop tutorial for new users',
    updatedAt: '2024-09-24 02:30 PM',
    status: 'completed',
    priority: 'low',
    dueDate: '2024-09-24',
  },
  {
    id: 19,
    title: 'Monitor server uptime',
    description: 'Ensure no downtime over the weekend',
    updatedAt: '2024-09-26 09:50 AM',
    status: 'pending',
    priority: 'medium',
    dueDate: '2024-09-28',
  },
  {
    id: 20,
    title: 'Write blog post',
    description: 'Publish article about new release',
    updatedAt: '2024-09-23 11:30 AM',
    status: 'completed',
    priority: 'low',
    dueDate: '2024-09-23',
  },
];
export { statusOptions, priorityOptions ,sampleTasks};
